name: darktar
description: A self-hosted private package registry for Dart and Flutter.
version: 0.1.0
repository: https://github.com/fres-sudo/darktar

environment:
  sdk: ^3.5.0

dependencies:
  archive: ^3.6.1
  crypto: ^3.0.5
  dotenv: ^4.2.0
  drift: ^2.22.1
  markdown: ^7.2.2
  mustache_template: ^2.0.0
  path: ^1.9.0
  pub_semver: ^2.1.4
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.28
  uuid: ^4.5.1
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  drift_dev: ^2.22.1
  lints: ^5.0.0
  mockito: ^5.4.4
  test: ^1.25.8

executables:
  darktar: server
